version: "3.8"

services:
  web:
    build:
      context: ./
      dockerfile: ./web/Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - elasticsearch

  elasticsearch:
    image: 'elasticsearch:7.9.2'
    environment:
      - discovery.type=single-node
    ports:
      - '9200:9200'
    volumes:
      - es-data:/usr/share/elasticsearch/data

volumes:
  es-data:
    driver: local
